version: 2.1
jobs:
  create_and_deploy_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Bucket
          command: |
            aws cloudformation deploy \
              --template-file bucket.yml \
              --stack-name ${CIRCLE_WORKFLOW_ID}\
              --parameter-overrides NAME="${CIRCLE_WORKFLOW_ID}"\
              --region us-east-1

      - run: aws s3 sync . s3://"${CIRCLE_WORKFLOW_ID}" --delete
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create CloudFont Distribution
          command: |
            aws cloudformation deploy \
              --template-file cloudfront.yml\
              --stack-name cloudfront\
              --paramete-overrides NAME="${CIRCLE_WORKFLOW_ID}"\
              --region us-east-1            

workflows:
  my_workflow:
    jobs:
      - create_and_deploy_frontend
      - promote_to_production:
          requires: [create_and_deploy_frontend]
