version: 2.1
jobs:
  create_and_deploy_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: create_stack
          command: |      
            aws cloudformation deploy \
              --template-file bucket.yml \
              --stack-name bucket \
              --parameter-overrides NAME=prod-${CIRCLE_WORKFLOW_ID}
      - run: aws s3 sync . s3://prod-${CIRCLE_WORKFLOW_ID} --delete

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: create_stack2
          command: |
            aws cloudformation deploy \
              --template-file cloudformation.yml \
              --stack-name cloudfront \
              --parameter-overrides PipelineID=prod-${CIRCLE_WORKFLOW_ID}

workflows:
   default:
     jobs:
       - create_and_deploy_frontend
       - promote_to_production:
           requires: 
             - create_and_deploy_frontend
